import React, { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import EducationState from "../../components/education/EducationState";
import { collection, educationApi } from "../../services/education";

export default function ClassesPage() {
  const [profile, setProfile] = useState(null); const [classes, setClasses] = useState([]); const [grades, setGrades] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [feedback, setFeedback] = useState(""); const [form, setForm] = useState({ name: "", description: "", grade: "" }); const [code, setCode] = useState("");
  const load = useCallback(() => { setLoading(true); setError(""); Promise.all([educationApi.getEducationProfile(), educationApi.getClassrooms(), educationApi.getGrades()]).then(([profileResponse, classResponse, gradeResponse]) => { setProfile(profileResponse.data); setClasses(collection(classResponse)); setGrades(collection(gradeResponse)); }).catch(() => setError("Não foi possível carregar suas turmas.")).finally(() => setLoading(false)); }, []); useEffect(load, [load]);
  const changeRole = async (role) => { setFeedback(""); try { const response = await educationApi.updateEducationProfile(role); setProfile(response.data); } catch (requestError) { setFeedback(requestError.response?.data?.role?.[0] || "Não foi possível alterar o perfil."); } };
  const create = async (event) => { event.preventDefault(); setFeedback(""); try { await educationApi.createClassroom({ ...form, grade: Number(form.grade) }); setForm({ name: "", description: "", grade: "" }); setFeedback("Turma criada com sucesso."); load(); } catch { setFeedback("Não foi possível criar a turma."); } };
  const join = async (event) => { event.preventDefault(); setFeedback(""); try { await educationApi.joinClassroom(code); setCode(""); setFeedback("Você entrou na turma."); load(); } catch (requestError) { setFeedback(requestError.response?.data?.detail || "Código de turma inválido."); } };
  return <section className="page-content classes-page"><header className="page-hero"><div><span className="eyebrow">ENSINO E APRENDIZADO</span><h1>Turmas</h1><p>Ensine, aprenda e acompanhe a evolução em um só lugar.</p></div></header><EducationState loading={loading} error={error} loadingText="Carregando suas turmas..." onRetry={load}>{profile && <><section className="role-panel card"><div><span className="eyebrow">SEU PERFIL EDUCACIONAL</span><h2>Como você usa a plataforma?</h2></div><div className="role-options"><button className={profile.role === "student" ? "active" : "secondary-button"} onClick={() => changeRole("student")}>Aluno</button><button className={profile.role === "teacher" ? "active" : "secondary-button"} onClick={() => changeRole("teacher")}>Professor</button></div></section>{profile.role === "teacher" ? <form className="class-form card" onSubmit={create}><h2>Criar turma</h2><div className="class-form-fields"><label>Nome<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Série<select required value={form.grade} onChange={(event) => setForm({ ...form, grade: event.target.value })}><option value="">Selecione</option>{grades.map((grade) => <option key={grade.id} value={grade.id}>{grade.name}</option>)}</select></label><label className="wide">Descrição<textarea rows="3" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label></div><button type="submit">Criar turma</button></form> : <form className="join-form card" onSubmit={join}><div><h2>Entrar em uma turma</h2><p>Informe o código compartilhado pelo professor.</p></div><label><span className="sr-only">Código da turma</span><input required maxLength="6" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="Ex.: 7F4K92" /></label><button type="submit">Entrar</button></form>}{feedback && <p className="class-feedback" role="status">{feedback}</p>}<div className="section-heading classes-heading"><div><span className="eyebrow">MINHAS TURMAS</span><h2>{profile.role === "teacher" ? "Turmas que você ensina" : "Turmas em que você estuda"}</h2></div></div>{classes.length ? <div className="classroom-grid">{classes.map((classroom) => <article className="classroom-card card" key={classroom.id}><div><span className={classroom.active ? "status-pill" : "status-pill inactive"}>{classroom.active ? "Ativa" : "Inativa"}</span><h3>{classroom.name}</h3><p>{classroom.grade_name}</p></div><div className="classroom-stats"><span>{classroom.student_count} alunos</span>{profile.role === "teacher" && <code>{classroom.code}</code>}</div><Link className="button" to={`/classes/${classroom.id}`}>Abrir turma</Link></article>)}</div> : <div className="empty-state card"><h3>{profile.role === "teacher" ? "Você ainda não criou nenhuma turma." : "Você ainda não participa de nenhuma turma."}</h3></div>}</>}</EducationState></section>;
}
