import React, { useCallback, useEffect, useState } from "react";
import EducationState from "../../components/education/EducationState";
import TeachingRecommendation from "../../components/education/TeachingRecommendation";
import { collection, educationApi } from "../../services/education";

export default function TeachingPage() {
  const [classes, setClasses] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await educationApi.getClassrooms(); const summaries = collection(response); const details = await Promise.all(summaries.map((item) => educationApi.getClassroom(item.id))); setClasses(details.map((item) => item.data)); } catch { setError("Não foi possível carregar as recomendações das turmas."); } finally { setLoading(false); } }, []); useEffect(load, [load]);
  return <section className="page-content teaching-page"><header className="page-hero"><div><span className="eyebrow">MODO PROFESSOR</span><h1>O que ensinar agora?</h1><p>Recomendações individuais baseadas no desempenho real dos alunos das suas turmas.</p></div></header><EducationState loading={loading} error={error} loadingText="Analisando suas turmas..." onRetry={load}>{classes.length ? <div className="teaching-classes">{classes.map((classroom) => <section className="class-section card" key={classroom.id}><div className="section-heading"><div><span className="eyebrow">{classroom.grade_name}</span><h2>{classroom.name}</h2></div></div>{classroom.students.length ? <div className="teaching-list">{classroom.students.map((student) => <TeachingRecommendation key={student.id} classroomId={classroom.id} student={student} />)}</div> : <p className="muted">Esta turma ainda não possui alunos.</p>}</section>)}</div> : <div className="empty-state card"><h3>Nenhuma turma disponível.</h3><p>Crie uma turma e adicione alunos para receber recomendações.</p></div>}</EducationState></section>;
}
