import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import EducationState from "../../components/education/EducationState";
import { collection, educationApi } from "../../services/education";

const emptyForm = { name: "", birth_date: "", education_level: "", grade: "", active: true };
export default function ChildrenPage() {
  const [children, setChildren] = useState([]); const [levels, setLevels] = useState([]); const [grades, setGrades] = useState([]); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [feedback, setFeedback] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [childResponse, levelResponse, gradeResponse] = await Promise.all([educationApi.getChildren(), educationApi.getLevels(), educationApi.getGrades()]); setChildren(collection(childResponse)); setLevels(collection(levelResponse)); setGrades(collection(gradeResponse)); } catch { setError("Não foi possível carregar seus filhos."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const availableGrades = useMemo(() => grades.filter((grade) => String(grade.education_level) === String(form.education_level)), [grades, form.education_level]);
  const openCreate = () => { setEditing(null); setForm(emptyForm); setShowForm(true); setFeedback(""); };
  const openEdit = (child) => { setEditing(child.id); setForm({ name: child.name, birth_date: child.birth_date || "", education_level: child.education_level, grade: child.grade, active: child.active }); setShowForm(true); setFeedback(""); };
  const save = async (event) => { event.preventDefault(); setFeedback(""); const payload = { ...form, education_level: Number(form.education_level), grade: Number(form.grade), birth_date: form.birth_date || null }; try { if (editing) await educationApi.updateChild(editing, payload); else await educationApi.createChild(payload); setShowForm(false); setFeedback(editing ? "Dados do filho atualizados." : "Filho adicionado com sucesso."); load(); } catch (requestError) { setFeedback(requestError.response?.data?.grade?.[0] || "Não foi possível salvar os dados."); } };
  return <section className="page-content classes-page"><header className="page-hero"><div><span className="eyebrow">FAMÍLIA E APRENDIZADO</span><h1>Meus filhos</h1><p>Acompanhe a escolaridade, os estudos e as aulas de apoio de cada filho.</p></div><button onClick={openCreate}>Adicionar filho</button></header>{feedback && <p className="class-feedback" role="status">{feedback}</p>}{showForm && <form className="class-form card" onSubmit={save}><h2>{editing ? "Editar filho" : "Adicionar filho"}</h2><div className="class-form-fields"><label>Nome<input required maxLength="150" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Data de nascimento (opcional)<input type="date" value={form.birth_date} onChange={(e) => setForm({ ...form, birth_date: e.target.value })} /></label><label>Nível de ensino<select required value={form.education_level} onChange={(e) => setForm({ ...form, education_level: e.target.value, grade: "" })}><option value="">Selecione</option>{levels.map((level) => <option key={level.id} value={level.id}>{level.name}</option>)}</select></label><label>Série/ano<select required value={form.grade} onChange={(e) => setForm({ ...form, grade: e.target.value })}><option value="">Selecione</option>{availableGrades.map((grade) => <option key={grade.id} value={grade.id}>{grade.name}</option>)}</select></label>{editing && <label className="toggle-row"><span><strong>Cadastro ativo</strong></span><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} /></label>}</div><div className="study-form-actions"><button type="button" className="secondary-button" onClick={() => setShowForm(false)}>Cancelar</button><button>Salvar</button></div></form>}<EducationState loading={loading} error={error} loadingText="Carregando seus filhos..." onRetry={load}>{children.length ? <div className="classroom-grid">{children.map((child) => <article className="classroom-card card" key={child.id}><div><span className={child.active ? "status-pill" : "status-pill inactive"}>{child.active ? "Ativo" : "Inativo"}</span><h3>{child.name}</h3><p>{child.grade_name} · {child.education_level_name}</p></div><div className="child-card-actions"><button className="text-button" onClick={() => openEdit(child)}>Editar</button><Link className="button" to={`/children/${child.id}`}>Acompanhar</Link></div></article>)}</div> : <div className="empty-state card"><h3>Nenhum filho cadastrado.</h3><p>Adicione um filho para começar a organizar os estudos e aulas de apoio.</p></div>}</EducationState></section>;
}
