import api from "./api";

export const educationApi = {
  getChildren: () => api.get("/education/children/"),
  getChild: (id) => api.get(`/education/children/${id}/`),
  createChild: (data) => api.post("/education/children/", data),
  updateChild: (id, data) => api.patch(`/education/children/${id}/`, data),
  deleteChild: (id) => api.delete(`/education/children/${id}/`),
  getChildSubjects: (id) => api.get(`/education/children/${id}/subjects/`),
  getChildProgress: (id) => api.get(`/education/children/${id}/progress/`),
  getLevels: () => api.get("/education/levels/"),
  getGrades: () => api.get("/education/grades/"),
  getSubjects: () => api.get("/education/subjects/"),
  getGradeSubjects: (gradeId) => api.get(`/education/grades/${gradeId}/subjects/`),
  getUnits: (subjectId, gradeId) => api.get(`/education/subjects/${subjectId}/units/`, { params: { grade: gradeId } }),
  getTopics: () => api.get("/education/topics/"),
  getTopic: (topicId) => api.get(`/education/topics/${topicId}/`),
  getTopicLessons: (topicId) => api.get(`/education/topics/${topicId}/lessons/`),
  getLesson: (lessonId) => api.get(`/education/lessons/${lessonId}/`),
  getTopicExercises: (topicId) => api.get(`/education/topics/${topicId}/exercises/`),
  submitExerciseAnswer: (exerciseId, answer) => api.post(`/education/exercises/${exerciseId}/answer/`, { answer, child: Number(localStorage.getItem("study_active_child")) || undefined }),
  completeLesson: (lessonId) => api.post(`/education/lessons/${lessonId}/complete/`, { child: Number(localStorage.getItem("study_active_child")) || undefined }),
  getTopicProgress: (topicId) => api.get(`/education/progress/`, { params: { topic: topicId, child: Number(localStorage.getItem("study_active_child")) || undefined } }),
  getEducationProgress: () => api.get("/education/progress/", { params: { child: Number(localStorage.getItem("study_active_child")) || undefined } }),
  getEducationProfile: () => api.get("/education/profile/"),
  updateEducationProfile: (role) => api.patch("/education/profile/", { role }),
  getClassrooms: () => api.get("/education/classrooms/"),
  getClassroom: (id) => api.get(`/education/classrooms/${id}/`),
  createClassroom: (data) => api.post("/education/classrooms/", data),
  updateClassroom: (id, data) => api.patch(`/education/classrooms/${id}/`, data),
  joinClassroom: (code) => api.post("/education/classrooms/join/", { code }),
  leaveClassroom: (id) => api.post(`/education/classrooms/${id}/leave/`),
  getClassroomActivities: (id) => api.get(`/education/classrooms/${id}/activities/`),
  createClassroomActivity: (id, data) => api.post(`/education/classrooms/${id}/activities/`, data),
  getClassroomPerformance: (id) => api.get(`/education/classrooms/${id}/performance/`),
  startDiagnostic: (topicId) => api.post(`/education/topics/${topicId}/diagnostic/start/`, { child: Number(localStorage.getItem("study_active_child")) || undefined }),
  answerDiagnostic: (diagnosticId, exercise, answer) => api.post(`/education/diagnostics/${diagnosticId}/answer/`, { exercise, answer }),
  finishDiagnostic: (diagnosticId) => api.post(`/education/diagnostics/${diagnosticId}/finish/`),
  getDiagnosticResult: (diagnosticId) => api.get(`/education/diagnostics/${diagnosticId}/result/`),
  getQuestions: (params) => api.get("/education/questions/", { params }),
  getAssignments: () => api.get("/education/assignments/"),
  getAssignment: (id) => api.get(`/education/assignments/${id}/`),
  createAssignment: (data) => api.post("/education/assignments/", data),
  startAssignment: (id) => api.post(`/education/assignments/${id}/start/`),
  answerAssignment: (submissionId, exercise, answer) => api.post(`/education/student-assignments/${submissionId}/answer/`, { exercise, answer }),
  submitAssignment: (submissionId) => api.post(`/education/student-assignments/${submissionId}/submit/`),
  getAssignmentResults: (id) => api.get(`/education/assignments/${id}/results/`),
  getReviewQueue: () => api.get("/education/review/", { params: { child: Number(localStorage.getItem("study_active_child")) || undefined } }),
  getErrorNotebook: () => api.get("/education/review/errors/", { params: { child: Number(localStorage.getItem("study_active_child")) || undefined } }),
  getRecommendations: (params = {}) => api.get("/education/recommendations/", { params: { ...params, child: params.child || Number(localStorage.getItem("study_active_child")) || undefined } }),
  getLessonPlan: (topic, classroom) => api.get("/education/recommendations/lesson-plan/", { params: { topic, classroom, child: Number(localStorage.getItem("study_active_child")) || undefined } }),
};

export const collection = (response) => response.data?.results || response.data || [];
