import React, { useEffect, useState } from "react";
import { collection, educationApi } from "../../services/education";

export default function TeachingRecommendation({ classroomId, student }) {
  const [recommendation, setRecommendation] = useState(null); const [plan, setPlan] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { educationApi.getRecommendations({ classroom: classroomId, student: student.id }).then((response) => setRecommendation(collection(response)[0] || null)).catch(() => setError("Não foi possível calcular a recomendação.")).finally(() => setLoading(false)); }, [classroomId, student.id]);
  const prepare = async () => { setError(""); try { const response = await educationApi.getLessonPlan(recommendation.topic, classroomId); setPlan(response.data); } catch { setError("Não foi possível preparar o roteiro."); } };
  return <article className="teaching-recommendation"><div className="teaching-student"><span>{student.username.slice(0, 1).toUpperCase()}</span><div><strong>{student.username}</strong><small>{recommendation?.subject_name || "Analisando desempenho"}</small></div></div>{loading ? <p className="muted">Calculando recomendação...</p> : recommendation ? <><div className="teaching-topic"><div><span className={`priority-pill ${recommendation.priority}`}>{recommendation.priority === "high" ? "Prioridade alta" : recommendation.priority === "medium" ? "Prioridade média" : "Prioridade baixa"}</span><h3>Revisar {recommendation.topic_title}</h3><p>{recommendation.reason.replace("Você", student.username)}</p></div><strong>{recommendation.accuracy ?? 0}%</strong></div><button type="button" onClick={prepare}>Preparar aula</button>{plan && <div className="lesson-plan"><div><h4>Roteiro da aula</h4>{!plan.sufficient_material && <p className="plan-warning">O material cadastrado não cobre todas as etapas.</p>}</div><ol>{plan.steps.map((step) => <li key={step.key} className={!step.available ? "unavailable" : ""}><strong>{step.title}</strong>{step.content && <p>{step.content}</p>}{step.exercise && <p>{step.exercise}</p>}{step.exercises?.map((exercise) => <p key={exercise.id}>{exercise.statement}</p>)}{step.message && <small>{step.message}</small>}</li>)}</ol></div>}</> : <p className="muted">Ainda não há dados suficientes para recomendar um conteúdo.</p>}{error && <p className="form-error">{error}</p>}</article>;
}
