# Generated by Django 5.2.17 on 2026-08-08 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['user', 'date'], name='studies_stu_user_id_d5b6eb_idx'),
        ),
    ]
