# Generated by Django 5.2.17 on 2026-08-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_child_and_more'),
        ('studies', '0002_study_studies_stu_user_id_d5b6eb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='education.child'),
        ),
    ]
