# Generated by Django 5.2.17 on 2026-08-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_study_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='child',
        ),
    ]
