import React, { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import EducationState from "../../components/education/EducationState";
import { collection, educationApi } from "../../services/education";

export default function ActivitiesPage() {
  const [profile, setProfile] = useState(null); const [activities, setActivities] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(() => { setLoading(true); setError(""); Promise.all([educationApi.getEducationProfile(), educationApi.getAssignments()]).then(([profileResponse, assignmentResponse]) => { setProfile(profileResponse.data); setActivities(collection(assignmentResponse)); }).catch(() => setError("Não foi possível carregar as atividades.")).finally(() => setLoading(false)); }, []); useEffect(load, [load]);
  return <section className="page-content activities-page"><header className="page-hero"><div><span className="eyebrow">ATIVIDADES</span><h1>{profile?.role === "teacher" ? "Atividades criadas" : "Suas atividades"}</h1><p>{profile?.role === "teacher" ? "Acompanhe listas e resultados das suas turmas." : "Resolva as atividades enviadas pelos seus professores."}</p></div>{profile?.role === "teacher" && <Link className="button" to="/questions">Selecionar questões</Link>}</header><EducationState loading={loading} error={error} loadingText="Carregando atividades..." onRetry={load}>{activities.length ? <div className="activity-grid">{activities.map((activity) => <article className="activity-card card" key={activity.id}><div><span className="eyebrow">{activity.classroom_name || "RASCUNHO"}</span><h2>{activity.title}</h2>{activity.description && <p>{activity.description}</p>}</div><div className="activity-details"><span>{activity.question_count} questões</span><span>{activity.due_date ? `Prazo: ${new Date(activity.due_date).toLocaleString("pt-BR")}` : "Sem prazo"}</span></div><Link className="button" to={`/activities/${activity.id}`}>{profile?.role === "teacher" ? "Ver resultados" : "Abrir atividade"}</Link></article>)}</div> : <div className="empty-state card"><h3>Nenhuma atividade disponível.</h3>{profile?.role === "teacher" && <Link className="button" to="/questions">Criar primeira atividade</Link>}</div>}</EducationState></section>;
}
