# Generated by Django 5.2.17 on 2026-08-10 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_assignment_assignmentexercise_assignment_exercises_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='lessonprogress',
            name='unique_lesson_progress_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='topicprogress',
            name='unique_topic_progress_per_user',
        ),
        migrations.RemoveIndex(
            model_name='exerciseattempt',
            name='education_e_user_id_c144e0_idx',
        ),
        migrations.AddField(
            model_name='child',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='education.educationlevel'),
        ),
        migrations.AddField(
            model_name='child',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='education.grade'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticassessment',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_assessments', to='education.child'),
        ),
        migrations.AddField(
            model_name='exerciseattempt',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to='education.child'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='education.child'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='education.child'),
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', 'child', 'exercise', 'attempted_at'], name='education_e_user_id_dd9e5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', True)), fields=('user', 'lesson'), name='unique_lesson_progress_per_user'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('user', 'child', 'lesson'), name='unique_lesson_progress_per_user_child'),
        ),
        migrations.AddConstraint(
            model_name='topicprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', True)), fields=('user', 'topic'), name='unique_topic_progress_per_user'),
        ),
        migrations.AddConstraint(
            model_name='topicprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('user', 'child', 'topic'), name='unique_topic_progress_per_user_child'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['parent', 'active'], name='education_c_parent__04320b_idx'),
        ),
    ]
