# Generated by Django 5.2.17 on 2026-08-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='education.educationlevel'),
        ),
        migrations.AlterField(
            model_name='child',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='education.grade'),
        ),
    ]
