# Generated by Django 5.2.17 on 2026-08-10 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_seed_education_levels_and_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='common_mistakes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='importance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='joint_activity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='parent_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='parent_tip',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=80)),
                ('source', models.CharField(max_length=200)),
                ('source_url', models.URLField(max_length=500)),
                ('region', models.CharField(default='Brasil', max_length=120)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('name', 'version'),
                'constraints': [models.UniqueConstraint(fields=('name', 'version', 'region'), name='unique_curriculum_version_region')],
            },
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_subjects', to='education.curriculum'),
        ),
        migrations.CreateModel(
            name='KnowledgeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_objects', to='education.curriculum')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_objects', to='education.unit')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='knowledge_objects',
            field=models.ManyToManyField(blank=True, related_name='topics', to='education.knowledgeobject'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='education.curriculum')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='education.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='education.subject')),
            ],
            options={
                'ordering': ('order', 'code'),
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='topics', to='education.skill'),
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('problem', models.TextField()),
                ('steps', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_examples', to='education.lesson')),
            ],
            options={
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('lesson', 'order'), name='unique_example_order_per_lesson')],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgeobject',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_knowledge_object_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('curriculum', 'code'), name='unique_skill_code_per_curriculum'),
        ),
    ]
