# Generated by Django 5.2.17 on 2026-08-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_lesson_common_mistakes_lesson_importance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesubject',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
