# Generated by Django 5.2.17 on 2026-08-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_gradesubject_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('published', 'Publicado')], db_index=True, default='published', max_length=12),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('published', 'Publicado')], db_index=True, default='published', max_length=12),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('published', 'Publicado')], db_index=True, default='published', max_length=12),
        ),
    ]
