# Generated by Django 5.2.17 on 2026-08-15 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_unpublish_incomplete_topics'),
        ('studies', '0004_remove_study_child'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lessonprogress',
            name='unique_lesson_progress_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='lessonprogress',
            name='unique_lesson_progress_per_user_child',
        ),
        migrations.RemoveConstraint(
            model_name='topicprogress',
            name='unique_topic_progress_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='topicprogress',
            name='unique_topic_progress_per_user_child',
        ),
        migrations.RemoveIndex(
            model_name='exerciseattempt',
            name='education_e_user_id_dd9e5e_idx',
        ),
        migrations.RemoveField(
            model_name='child',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='child',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='topicprogress',
            name='child',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='child',
        ),
        migrations.RemoveField(
            model_name='diagnosticassessment',
            name='child',
        ),
        migrations.RemoveField(
            model_name='exerciseattempt',
            name='child',
        ),
        migrations.AddIndex(
            model_name='exerciseattempt',
            index=models.Index(fields=['user', 'exercise', 'attempted_at'], name='education_e_user_id_c144e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_lesson_progress_per_user'),
        ),
        migrations.AddConstraint(
            model_name='topicprogress',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_topic_progress_per_user'),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
