import React, { useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import Breadcrumb from "../../components/education/Breadcrumb";
import DiagnosticQuestion from "../../components/education/DiagnosticQuestion";
import ProgressBar from "../../components/education/ProgressBar";
import { educationApi } from "../../services/education";

export default function DiagnosticPage() {
  const { topicId } = useParams(); const location = useLocation(); const topic = location.state?.topic; const [assessment, setAssessment] = useState(null); const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(null); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const start = async () => { setLoading(true); setError(""); try { const response = await educationApi.startDiagnostic(topicId); setAssessment(response.data); } catch (requestError) { setError(requestError.response?.data?.detail || "Não foi possível iniciar o diagnóstico."); } finally { setLoading(false); } };
  const submit = async (event) => { event.preventDefault(); const question = assessment.questions[index]; if (answer === null || answer === "") return; setLoading(true); setError(""); try { await educationApi.answerDiagnostic(assessment.id, question.exercise.id, answer); if (index === assessment.questions.length - 1) { const response = await educationApi.finishDiagnostic(assessment.id); setResult(response.data); } else { setIndex(index + 1); setAnswer(null); } } catch (requestError) { setError(requestError.response?.data?.detail || "Não foi possível salvar sua resposta."); } finally { setLoading(false); } };
  const question = assessment?.questions[index]; const percentage = assessment ? ((index + (result ? 1 : 0)) / assessment.questions.length) * 100 : 0;
  return <section className="page-content education-page diagnostic-page"><Breadcrumb items={[{ label: topic?.title, to: `/learn/topic/${topicId}`, state: location.state }, { label: "Diagnóstico" }]} />{result ? <article className="diagnostic-result card"><span className="eyebrow">RESULTADO DO DIAGNÓSTICO</span><h1>{Math.round(Number(result.percentage))}%</h1><p className="diagnostic-level">Nível: <strong>{result.level_display}</strong></p><div className="diagnostic-result-grid"><section><h2>Pontos fortes</h2>{result.strengths.length ? <ul>{result.strengths.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Nenhum ponto dominado foi identificado ainda.</p>}</section><section><h2>Conteúdos para revisar</h2>{result.review.length ? <ul>{result.review.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Você demonstrou domínio dos conteúdos avaliados.</p>}</section></div><div className="recommendation"><span className="eyebrow">RECOMENDAÇÃO</span><p>{result.recommendation.message}</p></div><Link className="button" to={result.recommendation.lesson_id ? `/learn/lesson/${result.recommendation.lesson_id}` : `/learn/topic/${topicId}`} state={location.state}>Começar estudo</Link></article> : !assessment ? <article className="diagnostic-intro card"><span className="eyebrow">AVALIAÇÃO DIAGNÓSTICA</span><h1>Descubra quanto você já sabe</h1><p>Responda de 5 a 10 questões sobre {topic?.title || "este conteúdo"}. O resultado ajudará a indicar o melhor ponto para começar.</p>{error && <p className="form-error">{error}</p>}<button type="button" onClick={start} disabled={loading}>{loading ? "Preparando questões..." : "Iniciar diagnóstico"}</button></article> : <form className="diagnostic-flow card" onSubmit={submit}><div className="diagnostic-head"><span className="eyebrow">QUESTÃO {index + 1} DE {assessment.questions.length}</span><ProgressBar value={percentage} label="Diagnóstico" /></div><DiagnosticQuestion question={question} value={answer} onChange={setAnswer} disabled={loading} />{error && <p className="form-error">{error}</p>}<div className="diagnostic-actions"><span className="muted">Responda com o que você já sabe.</span><button type="submit" disabled={loading || answer === null || answer === ""}>{loading ? "Salvando..." : index === assessment.questions.length - 1 ? "Ver resultado" : "Próxima questão"}</button></div></form>}</section>;
}
