import React, { useCallback, useEffect, useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import Breadcrumb from "../../components/education/Breadcrumb";
import EducationState from "../../components/education/EducationState";
import ProgressBar from "../../components/education/ProgressBar";
import { collection, educationApi } from "../../services/education";

const blocks = [["introduction", "Introdução"], ["explanation", "Explicação"], ["examples", "Exemplos"], ["summary", "Resumo"]];

export default function LessonPage() {
  const { lessonId } = useParams(); const location = useLocation(); const context = location.state || {}; const [lesson, setLesson] = useState(null); const [lessons, setLessons] = useState(context.lessons || []); const [progress, setProgress] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [completed, setCompleted] = useState(false); const [error, setError] = useState(""); const [feedback, setFeedback] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const lessonResponse = await educationApi.getLesson(lessonId); const selected = lessonResponse.data; const [lessonListResponse, progressResponse] = await Promise.all([educationApi.getTopicLessons(selected.topic), educationApi.getTopicProgress(selected.topic)]); setLesson(selected); setLessons(collection(lessonListResponse)); setProgress(collection(progressResponse).find((item) => item.topic === selected.topic) || null); let stored = []; try { stored = JSON.parse(sessionStorage.getItem("education_completed_lessons") || "[]"); } catch { /* ignore invalid session data */ } setCompleted(stored.includes(selected.id)); } catch { setError("Não foi possível carregar esta aula."); } finally { setLoading(false); } }, [lessonId]); useEffect(load, [load]);
  const markComplete = async () => { setSaving(true); setFeedback(""); try { await educationApi.completeLesson(lesson.id); const stored = new Set(JSON.parse(sessionStorage.getItem("education_completed_lessons") || "[]")); stored.add(lesson.id); sessionStorage.setItem("education_completed_lessons", JSON.stringify([...stored])); setCompleted(true); setFeedback("Aula marcada como concluída."); const response = await educationApi.getTopicProgress(lesson.topic); setProgress(collection(response).find((item) => item.topic === lesson.topic) || null); } catch { setFeedback("Não foi possível concluir a aula. Tente novamente."); } finally { setSaving(false); } };
  const index = lessons.findIndex((item) => item.id === lesson?.id); const previous = index > 0 ? lessons[index - 1] : null; const next = index >= 0 && index < lessons.length - 1 ? lessons[index + 1] : null; const navState = { ...context, topic: context.topic, lessons };
  return <section className="page-content education-page lesson-page"><Breadcrumb items={[{ label: context.gradeSubject?.subject.name, to: context.gradeSubject && `/learn/subject/${context.gradeSubject.id}`, state: context }, { label: context.topic?.title, to: lesson && `/learn/topic/${lesson.topic}`, state: context }, { label: lesson?.title }]} /><EducationState loading={loading} error={error} loadingText="Carregando aula..." onRetry={load}>{lesson && <><header className="lesson-header"><div><span className="eyebrow">AULA {index >= 0 ? index + 1 : ""}</span><h1>{lesson.title}</h1>{lesson.estimated_minutes > 0 && <p>{lesson.estimated_minutes} minutos estimados</p>}</div><ProgressBar value={progress?.completion_percentage} label="Progresso do conteúdo" /></header><article className="lesson-content card">{blocks.map(([field, title], blockIndex) => lesson[field] ? <section key={field}><span className="lesson-block-number">{blockIndex + 1}</span><div><h2>{title}</h2><p>{lesson[field]}</p></div></section> : null)}</article>{feedback && <p className={completed ? "success-message" : "form-error"} role="status">{feedback}</p>}<nav className="lesson-navigation" aria-label="Navegação entre aulas">{previous ? <Link className="button secondary-button" to={`/learn/lesson/${previous.id}`} state={navState}>← Aula anterior</Link> : <span />}{!completed ? <button type="button" onClick={markComplete} disabled={saving}>{saving ? "Salvando..." : "Marcar como concluída"}</button> : <span className="completed-mark lesson-complete">✓ Concluída</span>}{next ? <Link className="button" to={`/learn/lesson/${next.id}`} state={navState}>Próxima aula →</Link> : <Link className="button" to={`/learn/topic/${lesson.topic}`} state={context}>Ver exercícios →</Link>}</nav></>}</EducationState></section>;
}
