import React, { useCallback, useEffect, useState } from "react";
import { useLocation, useParams } from "react-router-dom";
import Breadcrumb from "../../components/education/Breadcrumb";
import EducationState from "../../components/education/EducationState";
import UnitSection from "../../components/education/UnitSection";
import { collection, educationApi } from "../../services/education";

export default function SubjectPage() {
  const { gradeSubjectId } = useParams(); const location = useLocation(); const [link, setLink] = useState(location.state?.gradeSubject); const [grade, setGrade] = useState(location.state?.grade); const [units, setUnits] = useState([]); const [topics, setTopics] = useState([]); const [progress, setProgress] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { let selectedLink = location.state?.gradeSubject; let selectedGrade = location.state?.grade; if (!selectedLink) { const grades = collection(await educationApi.getGrades()); const responses = await Promise.all(grades.map((item) => educationApi.getGradeSubjects(item.id))); grades.some((item, index) => { const found = collection(responses[index]).find((candidate) => String(candidate.id) === gradeSubjectId); if (found) { selectedLink = found; selectedGrade = item; return true; } return false; }); } if (!selectedLink) throw new Error("missing"); const [unitResponse, topicResponse, progressResponse] = await Promise.all([educationApi.getUnits(selectedLink.subject.id, selectedGrade.id), educationApi.getTopics(), educationApi.getEducationProgress()]); setLink(selectedLink); setGrade(selectedGrade); setUnits(collection(unitResponse)); setTopics(collection(topicResponse)); setProgress(collection(progressResponse)); } catch { setError("Não foi possível carregar este conteúdo."); } finally { setLoading(false); } }, [gradeSubjectId, location.state]); useEffect(() => { load(); }, [load]);
  const progressByTopic = Object.fromEntries(progress.map((item) => [item.topic, item])); const context = { gradeSubject: link, grade };
  return <section className="page-content education-page"><Breadcrumb items={[{ label: grade?.name, to: grade && `/learn/grade/${grade.id}`, state: { grade } }, { label: link?.subject.name }]} /><header className="page-hero"><div><span className="eyebrow">{grade?.name || "MATÉRIA"}</span><h1>{link?.subject.name || "Unidades"}</h1><p>{link?.subject.description || "Explore as unidades e escolha um conteúdo para estudar."}</p></div></header><EducationState loading={loading} error={error} loadingText="Carregando unidades..." onRetry={load}>{units.length ? <div className="unit-stack">{units.map((unit) => <UnitSection key={unit.id} unit={unit} topics={topics.filter((topic) => topic.unit === unit.id)} progressByTopic={progressByTopic} context={{ ...context, unit }} />)}</div> : <div className="empty-state card"><h3>Nenhuma unidade cadastrada para esta matéria.</h3></div>}</EducationState></section>;
}
