# Generated by Django 5.2.17 on 2026-08-10 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('system', 'Sistema')], default='system', max_length=10)),
                ('language', models.CharField(choices=[('pt-BR', 'Português (Brasil)')], default='pt-BR', max_length=10)),
                ('daily_study_goal_minutes', models.PositiveIntegerField(default=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
